title: "関西万博パビリオンブログ"
description: "関西万博の全てを紹介"
baseurl: "/pavilion_blog"
url: "https://zin1985.github.io"
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
